[package]
name = "day1-first"
version = "0.1.0"
authors = ["Christian Svensson <blue@cmd.nu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
